sudo: false
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
git:
  # don't need the default depth of 50
  # but don't want to use a depth of 1 since that affects
  # whether jobs run when you have multiple commits queued
  # https://github.com/travis-ci/travis-ci/issues/4575
  depth: 10
cache:
  pip: true
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install tox-travis
  - pip install .
script:
  - tox
after_success: coveralls