[tool.poetry]
name = "gtfparse"
version = "1.5.2"
description = "Parsing of General Transfer Format(GTF)/General Feature Format 3 (GFF3) genetic annotation files"
authors = ["Alex Rubinsteyn <alex.rubinsteyn@gmail.com>", "Miles Smith <miles-smith@omrf.org>"]
maintainers = ["Miles Smith <miles-smith@omrf.org>"]
license = "Apache-2.0"
classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Operating System :: OS Independent",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: Apache Software License",
        "Programming Language :: Python",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Operating System :: MacOS :: MacOS X",
        "Operating System :: POSIX :: Linux",
    ]
include = ["gtfparse/tests/data/*.*"]
homepage = "https://github.com/milescsmith/gtfparse"
repository = "https://github.com/milescsmith/gtfparse"
readme = "README.rst"
keywords = ["annotation", "gtf", "gff3", "bioinformatics"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.1"
pandas = "^1.3.1"
tqdm = "^4.61.2"
swifter = { version = "^1.0.0", optional = true }
dask = { version = "^2.25.0", optional = true}
coloredlogs = "^15.0.1"

[tool.poetry.extras]
parallel = ["swifter", "dask"]

[tool.poetry.dev-dependencies]
black = "^21.7b0"
flake8 = "^3.9.2"
pyre-check = "^0.9.3"
isort = "^5.9.2"
mypy = "^0.910"
ipython = "^7.25.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
