[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ['py37', 'py38']
skip-string-normalization = true

[tool.setuptools_scm]
write_to = "src/gtfparse/version.py"